name: Cucumber

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version: [14.x, 16.x, 17.x, 18.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: with Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - run: yarn install
    - name: Run E2E Testing
      run: yarn test:e2e -f json:cucumber-report.json -f progress-bar
    - uses: deblockt/cucumber-report-annotations-action@v1.7
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "**/cucumber-report.json"
